// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABxFpY6r2MY30k-qk99tICh0gmTS5MCXg',
    appId: '1:946413141417:web:a125d489aadcec2f8fd8b8',
    messagingSenderId: '946413141417',
    projectId: 'skillservice-22e0c',
    authDomain: 'skillservice-22e0c.firebaseapp.com',
    storageBucket: 'skillservice-22e0c.firebasestorage.app',
    measurementId: 'G-QWJZ5FD9EX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuC2F8yMciwpMVjEoysJNJ96yc-qnVEjc',
    appId: '1:946413141417:android:7013faa91d74cc0d8fd8b8',
    messagingSenderId: '946413141417',
    projectId: 'skillservice-22e0c',
    storageBucket: 'skillservice-22e0c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8xFYjWlpTmjVMmLkZ1bkcMqaZULhXzYw',
    appId: '1:946413141417:ios:abf55c93fcea7f658fd8b8',
    messagingSenderId: '946413141417',
    projectId: 'skillservice-22e0c',
    storageBucket: 'skillservice-22e0c.firebasestorage.app',
    iosClientId: '946413141417-8l5t2q7o7gktc5hene59dimnkvig2tpi.apps.googleusercontent.com',
    iosBundleId: 'com.example.skillserviceFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8xFYjWlpTmjVMmLkZ1bkcMqaZULhXzYw',
    appId: '1:946413141417:ios:abf55c93fcea7f658fd8b8',
    messagingSenderId: '946413141417',
    projectId: 'skillservice-22e0c',
    storageBucket: 'skillservice-22e0c.firebasestorage.app',
    iosClientId: '946413141417-8l5t2q7o7gktc5hene59dimnkvig2tpi.apps.googleusercontent.com',
    iosBundleId: 'com.example.skillserviceFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABxFpY6r2MY30k-qk99tICh0gmTS5MCXg',
    appId: '1:946413141417:web:25d22625485092958fd8b8',
    messagingSenderId: '946413141417',
    projectId: 'skillservice-22e0c',
    authDomain: 'skillservice-22e0c.firebaseapp.com',
    storageBucket: 'skillservice-22e0c.firebasestorage.app',
    measurementId: 'G-YNT8XXRFYJ',
  );
}
